config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for 	:users,
  						:path => '',
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                               :registrations => 'registrations'
              }

  resources :users, only: [:show]
  resources :pads
  resources :photos

  resources :pads do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :pads do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

end

app/models/pad.rb
class Pad < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :property_type, presence: true
  validates :pad_type, presence: true
  validates :accommodate, presence: true
  validates :total_pad, presence: true
  validates :pad_name, presence: true, length: {maximum: 50}
  validates :summary, presence: true, length: {maximum: 500}
  validates :address, presence: true
  validates :photos, presence: true
  validates :price, presence: true

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  before_action :set_pad, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @pads = Pad.all
  end

  def show
    @photos = @pad.photos

    @booked = Reservation.where("pad_id = ? AND user_id = ?", @pad.id, current_user.id).present? if current_user

    @reviews = @pad.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @pad = current_user.pads.build
  end

  def create
    @pad = current_user.pads.build(pad_params)

    if @pad.save
      if params[:images]
        params[:images].each do |image|
          @pad.photos.create(image: image)
        end
      end

      @photos = @pad.photos
      redirect_to edit_pad_path(@pad), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
    if current_user.id == @pad.user.id
      @photos = @pad.photos
    else
      redirect_to root_path, notice: "You don't have permission to do this."
    end
  end

  def update
    if @pad.update(pad_params)

      if params[:images]
        params[:images].each do |image|
          @pad.photos.create(image: image)
        end
      end

      redirect_to edit_pad_path(@pad), notice: "Updated..."
    else
      render :edit
    end
  end
  
  private
    def set_pad
      @pad = Pad.find(params[:id])
    end

    def pad_params
      params.require(:pad).permit(:property_type, :pad_type, :accommodate, :total_pad, :pad_name, :summary, :address, :is_food, :is_water, :is_ac, :is_heater, :is_toy, :is_treat, :is_walk, :price, :active)
    end
end

app/helpers/pads_helper.rb
module PadsHelper
end

app/views/pads/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Post your pad
  </div>
  <div class="panel body">
    <div class="container">
      <br>

      <%= form_for @pad, html: {multipart: true} do |f| %>

      <div class="row">
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Property Type</label>
            <%= f.select :property_type, [["Pet Shop", "Pet Shop"], ["Private Home", "Private Home"]], id: "property_type", prompt: "Select", class: "form-control" %>
          </div>
        </div>

        <div class="col-md-4 select">
          <div class="form-group">
            <label>Pad Type</label>
            <%= f.select :pad_type, [["Private Crate", "Private Crate"], ["Shared Crate", "Shared Crate"], ["Cage-Free Area", "Cage-Free Area"]], prompt: "Select", class: "form-control" %>
          </div>
        </div>

        <div class="col-md-4 select">
          <div class="form-group">
            <label>Total Pad Available</label>
            <%= f.select :total_pad, [["1 - 3","1 - 3"], ["4 - 6","4 - 6"], ["7 - 9", "7 - 9"], ["10 - 12", "10 - 12"]], prompt: "Select", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Accommodate</label>
            <%= f.select :accommodate, [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6 +","6 +"]], prompt: "Select", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
            <label>Pad Name</label>
            <%= f.text_field :pad_name, placeholder: "Pick an interesting name for your pad", class: "form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "Where is the pad located in?", class: "form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
            <label>Summary</label>
            <%= f.text_area :summary, placeholder: "Tell your prospective client more about the pad and your service", class: "form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <%= f.check_box :is_food %> Food
          </div>
          <div class="form-group">
            <%= f.check_box :is_water %> Water
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <%= f.check_box :is_treat %> Treat
          </div>
          <div class="form-group">
            <%= f.check_box :is_ac %> Air Conditioning
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <%= f.check_box :is_heater %> Heater
          </div>
          <div class="form-group">
            <%= f.check_box :is_toy %> Toys
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <%= f.check_box :is_walk %> Walk
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label>Nightly Price</label>
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= f.text_field :price, placeholder: "eg. $50", class: "form-control" %>
            </div>
          </div>
        </div>
      </div>

      <div id="photos"><%= render 'photos/list' %></div>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <span class="btn btn-default btn-file">
              <i class="fa fa-cloud-upload fa-lg"></i>Upload Photos
              <%= file_field_tag "images[]", type: :file, multiple: true%>
            </span>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.check_box :active %> Active
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pads/create.html.erb
<h1>Pads#create</h1>
<p>Find me in app/views/pads/create.html.erb</p>

app/views/pads/edit.html.erb
<%= render 'form' %>

app/views/pads/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Pads", pads_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Pet's Itinerary", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        List of Pads
      </div>
      <div class="panel-body">

        <% @pads.each do |pad| %>
        <div class="row">
          <div class="col-md-2">
            <%= link_to pad_path(pad) do %>
            <%= image_tag pad.photos[0].image.url(:thumb) if pad.photos.length > 0 %>
            <% end %>
          </div>
          <div class="col-md-7">
            <%= link_to pad_path(pad) do %>
            <h4><%= pad.pad_name %></h4>
            <% end %>
          </div>
          <div class="col-md-3 right">
            <%= link_to "Update", edit_pad_path(pad), class: "btn btn-primary" %>
          </div>
        </div>
        <hr>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pads/new.html.erb
<%= render 'form' %>

app/views/pads/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <!-- image -->
    <div class="row">
      <div class="col-md-12">
        <%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
      </div>
    </div>

    <br>
    <br>
    <!-- main info -->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 text-center" style="margin-top: 2em">

            <%= image_tag avatar_url(@pad.user), class: "img-circle avatar-large" %><br>
            <h6>Hosted by :</h6>
            <h4><%= link_to @pad.user.fullname, user_path(current_user.id) %></h4>
          </div>

          <div class="col-md-9">
            <h3><%= @pad.pad_name %></h3>
            <%= @pad.address %>

            <div class="row text-center row-space-1" style="margin-top: 3em">
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>

              <div class="row text-center">
                <div class="col-sm-3">
                  <%= @pad.property_type %>
                </div>
                <div class="col-sm-3">
                  <%= @pad.pad_type %>
                </div>
                <div class="col-sm-3">
                  <%= @pad.total_pad %> <%= @pad.total_pad > 1? "Total Pad" : "Total Pad" %>
                </div>
                <div class="col-sm-3">
                  <%= @pad.accommodate %> <%= @pad.accommodate > 1? "Pet" : "Pet" %>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <!-- Reservation form -->
        <%= render 'reservations/form' %>
      </div>
    </div>
    <br>
    <hr>
    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h2>About This Pad</h2>
        <p><%= @pad.summary %></p>
      </div>
    </div>
    <br>
    <!-- Facilities -->
    <div class="row">
      <div class="col-md-10">
        <div class="col-md-2">
          <h4>Facilities</h4>
        </div>
        <div class="col-md-10">
          <div class="row">
            <div class="col-md-6">
              <ul>
                <li class="<%= 'text-line-through' if !@pad.is_food %>">Food</li>
                <li class="<%= 'text-line-through' if !@pad.is_water %>">Water</li>
                <li class="<%= 'text-line-through' if !@pad.is_treat %>">Treat</li>
              </ul>
            </div>
            <div class="col-md-6">
              <li class="<%= 'text-line-through' if !@pad.is_ac %>">Air Conditioning</li>
              <li class="<%= 'text-line-through' if !@pad.is_heater %>">Heater</li>
              <li class="<%= 'text-line-through' if !@pad.is_toy %>">Toy</li>
              <li class="<%= 'text-line-through' if !@pad.is_walk %>">Walk</li>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br></br>
    <!-- Carousel -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

          <% if @photos %>
          <!-- Indicators -->
            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>
          <% end %>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <% if @photos %>
              <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
              <% end %>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
    </div>

    <br>
    <hr>

    <!-- Reviews -->
    <div class="row">
      <div class="col-md-12">
        <h3>Reviews <%= @pad.average_rating %> (<%= @reviews.count %>)</h3>
        <div class="container">
          <div>
            <%= render 'reviews/form' if @booked && !@hasReview %>
          </div>
          <div>
            <%= render 'reviews/list' %>
          </div>
        </div>
      </div>
    </div>

    <!-- Google map -->
    <div class="row">
      <div class="col-md-12">

        <div id="map"></div>
        <style>
          #map {
            width: 100%;
            height: 400px;
          }
        </style>
          <script>
            function initMap() {
              var mapDiv = document.getElementById('map');
              var map = new google.maps.Map(mapDiv, {
                  center: {lat: <%= @pad.latitude %>, lng: <%= @pad.longitude %>},
                  zoom: 14
              });
              var marker = new google.maps.Marker({
    		        	position: {lat: <%= @pad.latitude %>, lng: <%= @pad.longitude %>},
    		        	title: "Paw Pad is here!"
    		        });

    		        marker.setMap(map);
            }

        </script>
        <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5RTKb_SkM24pvC6qQ-sEfvr6_kFrRV3g&callback=initMap">
        </script>
      </div>
    </div>

    <!-- Nearby Pads -->
    <h3>Nearby Pads</h3>
    <div class="row">
      <% for pad in @pad.nearbys(10) %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag pad.photos[0].image.url(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to pad.pad_name, pad %><br>
              (<%= pad.distance.round(2) %> miles away)
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/pads/update.html.erb
<h1>Pads#update</h1>
<p>Find me in app/views/pads/update.html.erb</p>